id = "jupyter"
name = "Jupyter Notebook"
version = "0.1.1"
schema_version = 1
authors = ["KuaaMU<XCM853629353@OUTLOOK.com>"]
description = "Jupyter Notebook JSON Editor - Enhanced editing for .ipynb files with syntax highlighting and structure validation"
repository = "https://github.com/KuaaMU/jupyter-zed"

# This extension provides JSON editing capabilities for Jupyter Notebook files.
# Full notebook features (cell rendering, execution) require Zed Notebook API support.
# See: https://github.com/zed-industries/zed/issues/17325
