id = "jupyter"
name = "Jupyter Notebook"
version = "0.1.0"
schema_version = 1
authors = ["KuaaMU<XCM853629353@OUTLOOK.com>"]
description = "Jupyter Notebook support for Zed - syntax highlighting and basic editing for .ipynb files"
repository = "https://github.com/KuaaMU/jupyter-zed"

# Note: Zed has built-in JSON support
# We rely on Zed's native JSON grammar for .ipynb files
# Custom grammar will be added in Phase 2 if needed
